
name: synthesis

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: ghdl/synth:beta
    steps:
      - uses: actions/checkout@v1
      - name: Run synthesis
        run: cd syn && ./synth.sh
      - name: Upload result
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: syn/build/png_encoder.json
