name: tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  container:
    runs-on: ubuntu-latest
    container: ghdl/vunit:gcc-master
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          apt update
          apt install --yes python3-pil
      - name: Run tests
        run: |
          cd sim
          ./run_all.py -p4
