name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  container:
    runs-on: ubuntu-latest
    container: ghdl/vunit:gcc-master
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update
          apt install --yes python3-pil python3-requests
      - name: Run tests
        run: |
          cd sim
          python3 run_all.py -p4
